[package]
name = "obs-lenkeng"
version = "0.1.0"
authors = ["KOBA789 <kobahide789@gmail.com>"]

[lib]
name = "lenkeng"
crate-type = ["cdylib"]

[dependencies]
libobs-sys = { path = "../libobs-sys" }
libturbojpeg-sys = { path = "../libturbojpeg-sys" }
